In [1]:
import pandas as pd 
import pickle
import tensorflow as tf
from tensorflow.keras.models import load_model
import numpy as np

In [2]:
# load the trained model, scaler pickle and one-hot pickle
model = load_model('model.h5')

with open('scaler.pkl', 'rb') as file:
    scaler = pickle.load(file)

with open('onehot_encoder_geo.pkl', 'rb') as file:
    onehot_encoder_geo = pickle.load(file)

with open('label_encoder_gender.pkl', 'rb') as file:
    label_encoder_gender = pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [20]:
# example input data
data = {
    'CreditScore': 700,
    'Geography': 'France',
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 5,
    'Balance': 50000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 60000
}

In [8]:
# one-hot
geo_encoded = onehot_encoder_geo.transform([[data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))

c:\Users\prasa\Desktop\ml_projs\ANN_Classification\venv\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [22]:
data = pd.DataFrame(data, index=[0])
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,700,France,Male,40,5,50000,2,1,1,60000

In [23]:
data['Gender'] = label_encoder_gender.transform(data['Gender'])

In [24]:
data

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,700,France,1,40,5,50000,2,1,1,60000

In [25]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)

In [26]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,700,1,40,5,50000,2,1,1,60000,1.0,0.0,0.0

In [27]:
data_scaled = scaler.transform(data)

In [28]:
data_scaled

array([[ 0.50178794,  0.91324755,  0.10479359, -0.00134472, -0.41792108,
         0.80843615,  0.64920267,  0.97481699, -0.70296551,  1.00150113,
        -0.57946723, -0.57638802]])

In [29]:
# predict churn 
prediction = model.predict(data_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step

array([[0.02756405]], dtype=float32)